// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "command-line-arguments"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ItemRepository is an autogenerated mock type for the ItemRepository type
type ItemRepository struct {
	mock.Mock
}

// FetchAll provides a mock function with given fields:
func (_m *ItemRepository) FetchAll() ([]domain.ItemOutput, error) {
	ret := _m.Called()

	var r0 []domain.ItemOutput
	if rf, ok := ret.Get(0).(func() []domain.ItemOutput); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ItemOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: ctx
func (_m *ItemRepository) GetById(ctx context.Context) (domain.Item, error) {
	ret := _m.Called(ctx)

	var r0 domain.Item
	if rf, ok := ret.Get(0).(func(context.Context) domain.Item); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(domain.Item)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
